/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package maassystemoop;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user1
 */
public class JframeSystem extends javax.swing.JFrame {

    /**
     * Creates new form JframeSystem
     */
    public JframeSystem() {
        initComponents();
        Load();
    }
    int eID;
    public void Load()
    {
        ElemanIslemler dao = new ElemanIslemler();
        List<Eleman> list = dao.list();
        DefaultTableModel DFT = (DefaultTableModel) jTable1.getModel();
        DFT.setRowCount(0);
        for(Eleman st: list)
        {
            int sid = st.getId();
            String ElemanName = st.getEmpname();
            int maas = st.getSalary();
            int tel = st.getPhone();
            DFT.addRow(new Object[]{sid,ElemanName,maas,tel});
        }    
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtE_adi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txte_Tel = new javax.swing.JTextField();
        txte_Maas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        GuncelleButton = new javax.swing.JButton();
        AraButton = new javax.swing.JButton();
        EkleButton = new javax.swing.JButton();
        SilButton = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Maas Systym");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 6, 246, 77));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Eleman Adi");

        txtE_adi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Maas");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Tel");

        txte_Tel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txte_Maas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txte_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txte_Maas, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtE_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtE_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txte_Maas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txte_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 101, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Eleman id", "adi", "maas", "tel"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 101, 443, 188));

        GuncelleButton.setText("Guncelle");
        GuncelleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuncelleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(GuncelleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        AraButton.setText("Ara");
        AraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AraButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AraButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, -1, -1));

        EkleButton.setText("Ekle");
        EkleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EkleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EkleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        SilButton.setText("Sil");
        SilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SilButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SilButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        txtID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 170, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Eleman id");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EkleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EkleButtonActionPerformed
        // TODO add your handling code here:
        
Eleman e = new Eleman();
        
        String empname = txtE_adi.getText();
        int sal = Integer.parseInt(txte_Maas.getText());
        int phone  = Integer.parseInt(txte_Tel.getText());
        
        e.setEmpname(empname);
        e.setSalary(sal);
        e.setPhone(phone);
      
        ElemanIslemler dao = new ElemanIslemler();
        dao.save(e);
        Load();
        txtE_adi.setText("");
        txte_Maas.setText("");
        txte_Tel.setText("");
        txtE_adi.requestFocus();
    }//GEN-LAST:event_EkleButtonActionPerformed

    private void AraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AraButtonActionPerformed
        // TODO add your handling code here:
              eID = Integer.parseInt(txtID.getText());
 
        ElemanIslemler dao = new ElemanIslemler();
        Eleman st  = dao.get(eID);
 
        txtE_adi.setText(st.getEmpname());
        txte_Maas.setText(String.valueOf(st.getSalary()));
        txte_Tel.setText(String.valueOf(st.getPhone()));
    }//GEN-LAST:event_AraButtonActionPerformed

    private void GuncelleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuncelleButtonActionPerformed
        // TODO add your handling code here:
        Eleman st = new Eleman();
 
        String empname = txtE_adi.getText();
        int sal = Integer.parseInt(txte_Maas.getText());
        int phone = Integer.parseInt(txte_Tel.getText());
        
        st.setEmpname(empname);
        st.setSalary(sal);
        st.setPhone(phone);
        st.setId(eID);
        
        ElemanIslemler dao = new ElemanIslemler();
        dao.update(st);
         Load();
        txtE_adi.setText("");
        txte_Maas.setText("");
        txte_Tel.setText("");
        txtE_adi.requestFocus();
        txtID.setText("");
        
    }//GEN-LAST:event_GuncelleButtonActionPerformed

    private void SilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SilButtonActionPerformed
        // TODO add your handling code here:
        Eleman st = new Eleman();
        st.setId(eID);
        ElemanIslemler dao = new ElemanIslemler();
        dao.delete(st);
        Load();
        txtE_adi.setText("");
        txte_Maas.setText("");
        txte_Tel.setText("");
        txtE_adi.requestFocus();
        txtID.setText("");
    }//GEN-LAST:event_SilButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframeSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AraButton;
    private javax.swing.JButton EkleButton;
    private javax.swing.JButton GuncelleButton;
    private javax.swing.JButton SilButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtE_adi;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txte_Maas;
    private javax.swing.JTextField txte_Tel;
    // End of variables declaration//GEN-END:variables
}
